baseURL = 'https://arielassaf.com/'
languageCode = 'en-us'
title = 'Random thoughts'
theme = 'PaperMod'

[params]
defaultTheme = 'auto'
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
hidePoweredBy = true

# Social icons configuration - keeping it minimal with just the accounts you want
[[params.socialIcons]]
name = "github"
url = "https://github.com/ArielAssaf"

[[params.socialIcons]]
name = "linkedin"
url = "https://linkedin.com/in/arielassaf"

# Disable profile mode to prevent duplicate social icons
[params.profileMode]
enabled = false

# Home info params
[params.homeInfoParams]
Title = "Random thoughts"
Content = "This is where I share some random thoughts, experiences, and insights."
# Disable additional social icons on homepage
disableSpecingSocial = true

[params.footer]
powered = false
authored = false
copyright = false

[params.assets]
disableHLJS = true

[params.label]
text = ""

[menu]
[[menu.main]]
identifier = 'about'
name = 'About'
url = '/about/'
weight = 10

[[menu.main]]
identifier = 'posts'
name = 'Posts'
url = '/posts/'
weight = 20