baseURL = 'https://www.arielassaf.com/'
languageCode = 'en-us'
title = 'Ariel Assaf'
theme = 'PaperMod'

[params]
defaultTheme = 'auto'
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
hidePoweredBy = true

[params.homeInfoParams]
Title = 'Welcome to my blog'
Content = 'This is my personal website where I share my thoughts and experiences.'

[[params.socialIcons]]
name = "github"
url = "https://github.com/arielassaf"

[menu]
[[menu.main]]
identifier = 'about'
name = 'About'
url = '/about/'
weight = 10

[[menu.main]]
identifier = 'posts'
name = 'Posts'
url = '/posts/'
weight = 20
